services:
    acofinges_administracion.admin.evaluacion:
        class: AcofingesAdministracionBundle\Admin\EvaluacionAdmin
        arguments: [~, AcofingesAdministracionBundle\Entity\Evaluacion, AcofingesAdministracionBundle:EvaluacionAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, show_in_dashboard:false}
